---
#
# Ansible managed
#
repository:
  description: Ansible role to install CNI (Container Network Interface).
  homepage: https://buluma.github.io/
  topics: kubernetes, k8s, docker, container, containers, network, networking, connectivity, cni, containernetworking, ansible, molecule, tox, playbook
